### ISSUE TITLE
Fix deprecation warnings from @material-ui

### ISSUE THREAD

**Issue by wolfy1339** [hellomouse/GNS#156]
https://material-ui.com/style/typography/#migration-to-typography-v2

**Comment by handicraftsman** [comment]
Lol, i did that in particleplate some months ago

**Comment by handicraftsman** [comment]
This can be annoying if you have much typography widgets though.

**Comment by wolfy1339** [comment]
I don't think I have that many, and it's not that difficult, it's only the one attribute that needs to be changed
