### ISSUE TITLE
Assigned Events

### ISSUE THREAD

**Issue by BWBellairs** [hellomouse/GNS#7]
Catch assigned events and send to channel

**Comment by wolfy1339** [comment]
So it sends 2 nearly identical events.
We only need to relay once, since they all have the required info (`payload.issue.assignees`)
Check if the repo and issue number is the same (always cache last event of this type)

**Comment by wolfy1339** [comment]
Here's the diff link: https://www.diffchecker.com/WwXlsJlF

**Comment by wolfy1339** [comment]
Maybe even ping the user in question when we receive different events about the issue
