### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG 

### ISSUE THREAD

**Issue by handicraftsman** [hellomouse/GNS#97]
Getting this error while connecting to the web page:

![](https://i.imgur.com/R16KcK3.png)

**Comment by wolfy1339** [comment]
Ohhh. Dont use that URL, use this one:
http://github-notifucations.app

**Comment by handicraftsman** [comment]
![](https://i.imgur.com/kVBWjku.png)

**Comment by wolfy1339** [comment]
It's not ready for prime-time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
